### ISSUE TITLE
'Log Out' button malfunctions on mobile devices

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/eos_bank#12]
![image](https://user-images.githubusercontent.com/5037244/118874122-d75d3500-b8ea-11eb-9756-721fa1adc81b.png)
The log out button does not work properly on an android 11 chrome browser (or at least, mine)

More testing is required to confirm if other phones have similar issues.

Desktop does not suffer this issue and properly logs out the user when it is pressed.

If the button is disabled intentionally, it should be obscured from sight.

**Comment by SulpherStaer** [comment]
Correction - the desktop also suffers from this issue where it does not want to log out the user properly.

This occured in the following ways:

- Accessed the banking app via the Dashboard
- used the banking app, and pressed log out
- log out confirmed initially
- return to dashboard pane and refresh (to see if log out logged out the entire sso)
- observe dashboard still in customized user mode
- return to banking app and refresh
- observe banking app logging in the user automatically
- log out button no longer functions

**Comment by rolf-yoast** [comment]
No it can't log the user out if he/she's logged in through the dashboard. I must replace it with a go back to the dashboard button.

**Comment by WafflesMcDuff** [comment]
This will be closed by #10

**Comment by WafflesMcDuff** [comment]
This will be closed by https://github.com/eosfrontier/eos_bank/issues/10
